server.port: ${SERVER_PORT:5000}

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:bancoFiap}
      username: ${MONGO_USERNAME:root}
      password: ${MONGO_PASSWORD:root}
      authentication-database: ${MONGO_ADMIN_DATABASE:admin}